name: Update

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check:
    name: Check for new version
    outputs:
      update_available: ${{ steps.check.outputs.update_available }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - run: .github/workflows/check_update_available.bash
        id: check
      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        if: ${{ steps.check.outputs.update_available }}
        with:
          name: index.json
          path: index.json

  test:
    name: Build and test Nix flake
    needs: check
    if: ${{ needs.check.outputs.update_available == 'true' }}
    strategy:
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          name: index.json
      - uses: cachix/install-nix-action@daddc62a2e67d1decb56e028c9fa68344b9b7c2a
      - run: nix build -L -v .
      - run: nix flake check -L -v .

  deploy:
    name: Commit, tag and push changes
    needs: [check, test]
    if: ${{ needs.check.outputs.update_available == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          name: index.json
      - run: |
          git config user.name GitHub
          git config user.email noreply@github.com
      - run: .github/workflows/deploy_update.bash
