name: Update

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check:
    name: Check for new version
    outputs:
      update_available: ${{ steps.check.outputs.update_available }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - run: .github/workflows/check_update_available.bash
        id: check
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        if: ${{ steps.check.outputs.update_available }}
        with:
          name: index.json
          path: index.json

  test:
    name: Build and test Nix flake
    needs: check
    if: ${{ needs.check.outputs.update_available == 'true' }}
    strategy:
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: index.json
      - uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a
      - run: nix build -L -v .
      - run: nix flake check -L -v .

  deploy:
    name: Commit, tag and push changes
    needs: [check, test]
    if: ${{ needs.check.outputs.update_available == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: index.json
      - run: |
          git config user.name GitHub
          git config user.email noreply@github.com
      - run: .github/workflows/deploy_update.bash
